services:

  app:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: agenssistant
    command: sleep infinity
    user: root
    volumes:
      - ./:/workspace/agenssistant
    env_file: .env
